name: Build Android APK (Kivy + Buildozer)

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            zip unzip build-essential libffi-dev libssl-dev \
            autoconf libtool pkg-config git openjdk-17-jdk

      # ✅ Install stable Android SDK packages and accept licenses non-interactively
      - name: Set up Android SDK (stable)
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: latest
          packages: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0
          accept-licenses: true

      # (Optional) sanity check: list SDK packages / confirm aidl exists
      - name: Show installed SDK packages
        run: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --list | head -n 200 || true
          ls -la $ANDROID_SDK_ROOT/build-tools/34.0.0/aidl || true

      - name: Install Buildozer & tools
        run: |
          python -m pip install --upgrade pip
          pip install cython buildozer

      # ✅ Force Buildozer to use the SDK we just installed, not its private one
      - name: Build debug APK (accept SDK licenses)
        env:
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
          ANDROID_HOME: /usr/local/lib/android/sdk
          ANDROIDSDK: /usr/local/lib/android/sdk
        run: |
          # Prevent fallback to a half-installed private SDK
          rm -rf ~/.buildozer/android/platform/android-sdk || true

          # Build with verbose logs; auto-accept any remaining prompts
          echo y | buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: bin/*.apk
