name: Build Android APK (Kivy + Buildozer)

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            zip unzip build-essential libffi-dev libssl-dev \
            autoconf libtool pkg-config git openjdk-17-jdk

      # ✅ NEW: Install Android SDK + stable Build-Tools + accept licenses
      - name: Set up Android SDK (stable)
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: latest
          packages: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0
          accept-licenses: true

      # (Optional) show sdkmanager versions for sanity
      - name: Show installed SDK packages
        run: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --list | head -n 200 || true
          ls -la $ANDROID_SDK_ROOT/build-tools || true

      - name: Install Buildozer & tools
        run: |
          python -m pip install --upgrade pip
          pip install cython buildozer

      - name: Build debug APK (accept SDK licenses)
        env:
          # Ensure Buildozer uses the SDK we installed above
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
          ANDROIDSDK: /usr/local/lib/android/sdk
        run: |
          echo y | buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: bin/*.apk
